Repository sen-newface/qoo-cheese, pull requests merged in 2020-05, with the labels that each got.

#36 Issue#24：routes/api.phpにルーティングを定義する + それに伴うコントローラの作成
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/app/Http/Controllers/Api/PhotosController.php
  yeahcheese/app/Http/Controllers/Api/UsersController.php
  yeahcheese/routes/api.php
Labels: バックエンド

#50 Feature/create mutation types（ミューテーション名を定義しておくファイルを作成・編集）
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/mutation-types.js
  yeahcheese/resources/js/store/photos/actions.js
  yeahcheese/resources/js/store/photos/mutations.js
  yeahcheese/resources/js/store/users/actions.js
  yeahcheese/resources/js/store/users/mutations.js
Labels: バックエンド

#52 Feature/create header component（共通して利用するヘッダーの作成）
  yeahcheese/resources/js/app.vue
  yeahcheese/resources/js/components/CommonHeader.vue
Labels: フロントエンド

#67 Feature/create header component（ヘッダーコンポーネント作成）
  yeahcheese/resources/js/components/CommonHeader.vue
Labels: バグ修正

#69 Feature/issue#68 error handling and router guard
  yeahcheese/app/Http/Controllers/Api/AuthController.php
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/app.vue
  yeahcheese/resources/js/router/index.js
Labels: バックエンド, フロントエンド

#70 Feature/photos controller delete and add methods（仮のコントローラ定義とそのコントローラのテスト）
  yeahcheese/app/Http/Controllers/Api/PhotosController.php
  yeahcheese/app/Http/Requests/StorePhotoRequest.php
  yeahcheese/resources/js/CommonHeader.vue
  yeahcheese/tests/Feature/PhotoControllerTest.php
Labels: バックエンド

#96 js インデント修正
  .gitignore
  yeahcheese/resources/js/BaseEvent.vue
  yeahcheese/resources/js/CommonHeader.vue
  yeahcheese/resources/js/app.vue
  yeahcheese/resources/js/components/CommonHeader.vue
  yeahcheese/resources/js/pages/401.vue
  yeahcheese/resources/js/pages/403.vue
  yeahcheese/resources/js/pages/404.vue
  yeahcheese/resources/js/pages/500.vue
  yeahcheese/resources/js/pages/Login.vue
  yeahcheese/resources/js/pages/eventStore.vue
  yeahcheese/resources/js/pages/index.vue
  yeahcheese/resources/js/pages/register.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/tmpAuthTest.vue
Labels: リファクタリング

#77 Feature/issue#71 events index
  yeahcheese/.env.testing
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/app/Http/Resources/Event.php
  yeahcheese/database/factories/PhotoFactory.php
  yeahcheese/resources/js/BaseEvent.vue
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/components/BaseEvent.vue
  yeahcheese/resources/js/pages/eventShow.vue
  yeahcheese/resources/js/pages/eventsIndex.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/getters.js
  yeahcheese/resources/js/store/events/index.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/users/actions.js
  yeahcheese/resources/js/store/users/getters.js
  yeahcheese/tests/Feature/EventControllerTest.php
  yeahcheese/tests/Feature/ExampleTest.php
  yeahcheese/tests/Unit/ExampleTest.php
Labels: バックエンド, フロントエンド

#80 イベント詳細
  yeahcheese/.gitignore
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/app/Http/Controllers/Api/PhotosController.php
  yeahcheese/app/Http/Resources/Event.php
  yeahcheese/app/Http/Resources/Photo.php
  yeahcheese/database/factories/EventFactory.php
  yeahcheese/database/factories/PhotoFactory.php
  yeahcheese/resources/js/CommonHeader.vue
  yeahcheese/resources/js/components/CommonHeader.vue
  yeahcheese/resources/js/pages/eventShow.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/getters.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/photos/actions.js
  yeahcheese/resources/js/store/photos/getters.js
  yeahcheese/resources/js/store/photos/index.js
  yeahcheese/resources/js/store/photos/mutations.js
  yeahcheese/resources/js/store/users/actions.js
  yeahcheese/routes/api.php
  yeahcheese/tests/Feature/EventControllerTest.php
  yeahcheese/tests/Feature/PhotoControllerTest.php
Labels: バックエンド, フロントエンド

#82 Feature/issue#81 load component
  yeahcheese/.gitignore
  yeahcheese/public/image/load.gif
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/app.vue
  yeahcheese/resources/js/components/Load.vue
  yeahcheese/resources/js/store/index.js
  yeahcheese/resources/js/store/load.js
Labels: フロントエンド

#92 イベント削除機能実装
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/database/migrations/2020_05_21_005612_drop_photos_table.php
  yeahcheese/database/migrations/2020_05_21_005725_re_create_photos_table.php
  yeahcheese/tests/Feature/EventControllerTest.php
Labels: バックエンド

#107 localstorage の管理を vuex で
  yeahcheese/app/Http/Controllers/Api/AuthController.php
  yeahcheese/app/User.php
  yeahcheese/database/factories/UserFactory.php
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/app.js
  yeahcheese/resources/js/pages/index.vue
  yeahcheese/resources/js/store/index.js
  yeahcheese/resources/js/store/storage.js
Labels: バグ修正, バックエンド, フロントエンド

#114 Feature/issue#108 events index pagenation
  yeahcheese/app/User.php
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/components/CommonHeader.vue
  yeahcheese/resources/js/components/Pagenation.vue
  yeahcheese/resources/js/pages/eventStore.vue
  yeahcheese/resources/js/pages/eventsIndex.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/store/events/getters.js
  yeahcheese/resources/js/store/events/index.js
  yeahcheese/resources/js/store/events/mutations.js
Labels: フロントエンド

#118 Feature/issue#4 delete event
  yeahcheese/resources/js/components/flashMessage.vue
  yeahcheese/resources/js/pages/eventShow.vue
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/flashMessage.js
Labels: フロントエンド

#130 Feature/issue#122add photo from event show
  yeahcheese/app/Event.php
  yeahcheese/resources/js/components/Load.vue
  yeahcheese/resources/js/components/PreviewAndSavePhoto.vue
  yeahcheese/resources/js/pages/EventEdit.vue
  yeahcheese/resources/js/pages/eventShow.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/photos/actions.js
  yeahcheese/resources/js/store/photos/mutations.js
Labels: フロントエンド

#149 Refacta/issue#148 stop scrool on load
  yeahcheese/resources/js/components/Load.vue
  yeahcheese/resources/js/components/PreviewAndSavePhoto.vue
  yeahcheese/resources/js/mixins/scrollControllable.js
Labels: フロントエンド, リファクタリング

#141 Refacta/issue#139 error handling router guerd
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/resources/js/app.vue
  yeahcheese/resources/js/pages/404.vue
  yeahcheese/resources/js/pages/index.vue
  yeahcheese/resources/js/router/index.js
  yeahcheese/resources/js/store/events/getters.js
  yeahcheese/resources/js/store/events/index.js
  yeahcheese/resources/js/store/events/mutations.js
Labels: フロントエンド

#138 写真削除 + 写真プレビュー
  yeahcheese/app/Http/Controllers/Api/PhotosController.php
  yeahcheese/resources/js/components/PhotoList.vue
  yeahcheese/resources/js/components/PreviewAndSavePhoto.vue
  yeahcheese/resources/js/components/flashMessage.vue
  yeahcheese/resources/js/pages/eventShow.vue
  yeahcheese/resources/js/store/events/actions.js
  yeahcheese/resources/js/store/events/mutations.js
  yeahcheese/resources/js/store/photos/actions.js
  yeahcheese/resources/js/store/photos/getters.js
  yeahcheese/resources/js/store/photos/mutations.js
  yeahcheese/resources/views/welcome.blade.php
Labels: フロントエンド

#143 N + 1対策 とisOwner
  yeahcheese/app/Event.php
  yeahcheese/app/Http/Controllers/Api/EventsController.php
Labels: リファクタリング

#155 写真の複数枚投稿！
  docker/nginx/nginx.conf
  yeahcheese/app/Http/Controllers/Api/EventsController.php
  yeahcheese/app/Http/Controllers/Api/PhotosController.php
  yeahcheese/app/Http/Resources/Photo.php
  yeahcheese/database/migrations/2020_05_27_052748_add_title_to_photos_table.php
  yeahcheese/resources/js/api.js
  yeahcheese/resources/js/components/PhotoList.vue
  yeahcheese/resources/js/components/PreviewAndSavePhoto.vue
  yeahcheese/resources/js/pages/eventsIndex.vue
  yeahcheese/resources/js/store/photos/actions.js
  yeahcheese/resources/js/store/photos/getters.js
  yeahcheese/resources/js/store/photos/mutations.js
  yeahcheese/tests/Feature/PhotoControllerTest.php
Labels: バックエンド, フロントエンド

#164 formリクエストバグ修正
  yeahcheese/app/Http/Requests/EventRequest.php
  yeahcheese/app/Http/Requests/StoreEventRequest.php
  yeahcheese/app/Http/Requests/UpdateEventRequest.php
Labels: バグ修正
